# Generated by Django 2.2.14 on 2023-08-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(null='true', upload_to='gallery'),
            preserve_default='true',
        ),
    ]
