# Generated by Django 2.2.14 on 2023-09-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(null='true'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null='true'),
        ),
    ]
